Project Pipeline
finos/legend-sdlc pull request #223
Opened 2021-07-01 21:25 UTC by MauricioUyaguari

Adds project pipeline. 
See https://github.com/finos/legend-sdlc/issues/233

2021-07-12 21:57 UTC, kevin-m-knight-gs requested changes
This is not a complete review, but there are several comments here.

2021-07-12 21:57 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/finos/FinosFileLoader.java
> +public class FinosFileLoader
This should probably be package-private.

2021-07-12 21:57 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/finos/FinosFileLoader.java
> +    FinosFileLoader(ClassLoader classLoader, String fileName, String schemaSignature)
Rename "schemaSignature" to "fileExtension" to make it more clear.

2021-07-12 21:57 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructureExtensions.java
> +public class ProjectStructureExtensions
Does this have anything to do with the class ProjectStructureExtension? If not, then you should find a different name for this class.

2021-07-12 21:57 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/config/ProjectCreationConfiguration.java
> +    public static ProjectCreationConfiguration newConfig(@JsonProperty("defaultProjectStructureVersion") Integer defaultProjectStructureVersion, @JsonProperty("groupIdPattern") Pattern groupIdPattern
Why is this being moved away from the other factory methods?

2021-07-12 21:57 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/config/ProjectStructureExtensionsConfiguration.java
> +public class ProjectStructureExtensionsConfiguration
See my comment on ProjectStructureExtensions.

2021-07-14 22:01 UTC, MauricioUyaguari commented
add tests for serializer dependency

2021-07-14 22:06 UTC, kevin-m-knight-gs requested changes
Another incomplete review, but some comments.

2021-07-14 22:06 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectConfigurationUpdateBuilder.java
> +    }
Please change this method name to match whatever you change the other two to.

2021-07-14 22:06 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructure.java
> +        return PROJECT_STRUCTURE_FACTORY.newProjectStructure(projectConfiguration, null);
```suggestion
        return getProjectStructure(projectConfiguration, null);
```

2021-07-14 22:06 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/resources/org/finos/legend/sdlc/server/gitlab/finos/ci-settings-1.xml
> + Copyright 2020 Goldman Sachs
2021

2021-07-14 22:06 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/resources/org/finos/legend/sdlc/server/gitlab/finos/gitlab-ci-1.yml
> +# Copyright 2020 Goldman Sachs
2021

2021-07-26 21:03 UTC, kevin-m-knight-gs requested changes

2021-07-29 16:35 UTC, kevin-m-knight-gs requested changes
Just a few minor changes

2021-07-29 16:35 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/guice/AbstractBaseModule.java
> +    }
Let's only compute this once and store it in a field, similar to getProjectStructureExtensionProvider.

2021-07-29 16:35 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructurePlatformExtensions.java
> +    }
```suggestion
    public List<Platform> getPlatforms()
    {
        return Lists.mutable.withAll(this.platforms.values());
    }
```

2021-07-29 16:35 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/project/ProjectStructurePlatformExtensions.java
> +        }
Do we need to give access to this map? If not, then remove this method. If we do, then let's make sure it's unmodifiable (e.g., by wrapping it with Collections.unmodifiableMap).

2021-07-29 19:09 UTC, kevin-m-knight-gs approved these changes

2021-08-06 21:16 UTC, merged

2021-08-06 21:27 UTC, akphi commented
🎉 @MauricioUyaguari 🌮