Checking default protected branch for any operations
finos/legend-sdlc pull request #512
Opened 2022-09-09 13:55 UTC by itdnk

Checking default protected branch for any operations

2022-09-12 22:03 UTC, kevin-m-knight-gs requested changes
The biggest thing here is to try to avoid calling getDefaultBranch multiple times, since it makes a call to GitLab. Especially, try to avoid calling it repeated in a loop or stream.

Also, make sure you've converted all the places where MASTER_BRANCH was used. I noticed one place you missed, and perhaps there are more.

2022-09-12 22:03 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApi.java
> +            masterBranch = withRetries(() -> repositoryApi.getBranch(gitLabProjectId.getGitLabId(), getDefaultBranch(gitLabProjectId)));
Call getDefaultBranch outside withRetries. Also, let's rename the variable "masterBranch" to "defaultBranch".

2022-09-12 22:03 UTC, kevin-m-knight-gs commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApi.java
> +                workspaceCreationRevisionId = withRetries(() -> repositoryApi.getMergeBase(gitLabProjectId.getGitLabId(), Arrays.asList(getDefaultBranch(gitLabProjectId), currentWorkspaceRevisionId))
Try to avoid calling getDefaultBranch multiple times. You're already calling it on line 510.

2022-09-13 18:02 UTC, itdnk commented on legend-sdlc-server/src/main/java/org/finos/legend/sdlc/server/gitlab/api/GitLabWorkspaceApi.java
> +            workspaceCreationRevisionId = withRetries(() -> repositoryApi.getMergeBase(gitLabProjectId.getGitLabId(), Arrays.asList(getDefaultBranch(gitLabProjectId), currentWorkspaceRevisionId)).get
makes sense

2022-09-13 19:58 UTC, kevin-m-knight-gs approved these changes

2022-09-14 14:31 UTC, merged